[package]
name = "grand-line-examples-simple-todo"
version = "0.0.0"
edition = "2024"

[dependencies]
grand-line = { path = "../../grand-line", features = ["sqlite"] }
serde = { version = "1.0.219", default-features = false, features = ["derive", "std"] }
